### ISSUE TITLE
Blobxfer getting stuck when uploading Huge size files

### ISSUE THREAD

**Issue by Sagar2133** [Sagar2133/Blobxfer#1]
I’m trying to upload backup files from my local system to Azure Blob storage. But right now blobxfer able to push only megabyte size files on blob storage and gigabyte sizing files(size around 230+GB ) are keep on failing with below error. 
Currently we are using 33554432 bytes one_shot upload limit with 8388608 bytes chunk_size under the blobxfer configuration. 

ERROR - exceptions encountered while uploading
ERROR - [Errno 2] No such file or directory: ' <File_name_XYZ>
Traceback (most recent call last):
  File "blobxfer/operations/upload.py", line 1208, in start
  File "blobxfer/operations/upload.py", line 1171, in _run
  File "blobxfer/operations/upload.py", line 466, in _worker_thread_upload
  File "blobxfer/operations/upload.py", line 574, in _process_upload_descriptor
  File "blobxfer/models/upload.py", line 940, in read_data
  File "pathlib.py", line 1161, in open
  File "pathlib.py", line 1015, in _opener
  File "pathlib.py", line 387, in wrapped
FileNotFoundError: [Errno 2] No such file or directory: '<File_name_XYZ>'

Also, we have observed blobxfer keep on checking old file which was already removed from locally, hence after sometime execution failed with the above error.
So can you suggest how can we transfer a big size file to blob storage? Is there any additional parameter for this?

**Comment by Sagar2133** [comment]
Can any one assist me in this
